### ISSUE TITLE
Path to rsync

### ISSUE THREAD

**Issue by sporto** [moll/mina-rsync#1]
I am having the following error

-----> Copying from cache directory to build path
    rsync: --acls: unknown option
    rsync error: syntax or usage error (code 1) at /SourceCache/rsync/rsync-42/rsync/main.c(1333) [client=2.6.9]

Not sure if this is generated in my dev machine or the server, I assume this step happens on the server.

So the error seems to be with the version of rsync I presume.
I have a newer version of rsync installed, but it is in a different path. So mina seems to be using the old system rsync.

Is there an option in mina-rsync to provide the path to the rsync binary?

thanks

**Comment by moll** [comment]
Hey there!

Sorry for the trouble you're having! I was apparently too optimistically assuming every `rsync` on servers has ACL support built in. I'm not sure whether or how to handle that in the future, but for now I described the previously existing [`rsync_copy`](https://github.com/moll/mina-rsync#configuration) option in the README.

You can set `rsync_copy` to a value without the `--acl` flag or set it to use it your binary if you're using ACLs on your server:

``` ruby
set :rsync_copy, "/usr/local/bin/rsync --archive --acls --xattrs"
```

Let me know if that works for you!

**Comment by sporto** [comment]
That works, thanks, I just pointed rsync_copy to the newest version of rsync.
