### ISSUE TITLE
Execute something locally?

### ISSUE THREAD

**Issue by j6s** [moll/mina-rsync#13]
Hello,

I have a simple question: Is it possible to execute somthing locally, prior to rsyncing?
In my use case I would like to run my grunt tasks, so that my LESS in compiled and my Javascript minified. Is that possible?

**Comment by moll** [comment]
Hey!

Would the following paragraph be of any help? https://github.com/moll/mina-rsync/#precompile-assets-before-deploy

Cheers

**Comment by j6s** [comment]
yes, i read it just after writing it. I am sorry for saking

**Comment by moll** [comment]
No problem. Glad it helped. :)
