### ISSUE TITLE
undefined method `set_default' for main:Object (NoMethodError)

### ISSUE THREAD

**Issue by rubyconvict** [moll/mina-rsync#7]
I do not have anything like set_default :repository, "." in config/deploy.rb and I do have require "mina/rsync" in the file.

```
(...)/vendor/bundle/ruby/2.1.0/gems/mina-rsync-1.1.0/lib/mina/rsync.rb:8:in
`<top (required)>': undefined method `set_default' for main:Object
(NoMethodError)(...)
```

**Comment by moll** [comment]
Hey, sorry you're having trouble!
How are you executing that `config/deploy.rb`? By typing `mina` at the shell?

**Comment by rubyconvict** [comment]
It's worse than that, I can't start rails (4.1.0) server or console, when I remove mina-rsync, everything is back to normal. I have used the gem successfully before without rails (just with bundler) on some other project and I just moved everything to rails app.

**Comment by moll** [comment]
Could it be because Bundler is trying to load it from `Gemfile` while it's loading Rails? Could you try adding `:require => false` to that line in `Gemfile` and see if that fixes it for you?

**Comment by rubyconvict** [comment]
Helped. Thanks.

**Comment by moll** [comment]
Great to hear! :)

**Comment by tungpt247** [comment]
Great, helped. Thanks
