### ISSUE TITLE
fatal: Not a git repository: 'tmp/deploy/.git'

### ISSUE THREAD

**Issue by rubyconvict** [moll/mina-rsync#8]
$ mina deploy
-----> Staging...
fatal: Not a git repository: 'tmp/deploy/.git'
Git checkout: fatal: Not a git repository: 'tmp/deploy/.git'

Whatever surrouding git setup in deploy.rb I use or don't use, i get this error.

**Comment by rubyconvict** [comment]
When I removed (empty) directory tmp/deploy, everything started working again.

**Comment by moll** [comment]
Sorry for this stuff being fragile. I wrote it as a quick script. :-)
